version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  postgresql_exporter:
    image: schmiddim/postgresql-prometheus-adapter:v1.2.0
    restart: always
    environment: 
      DATABASE_URL: "user=postgres password=postgres host=db port=5432 database=postgres"
    ports: 
      - "9201:9201"
    depends_on: 
      - db
  adminer:
    image: adminer
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 8080:8080
    depends_on: 
      - db
volumes:
  db:
    driver: local